"""create save table

Revision ID: a8359ec43a23
Revises: 
Create Date: 2026-09-22 22:23:16.607663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8359ec43a23'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('save_name', sa.String(), nullable=False),
    sa.Column('trainer_name', sa.String(), nullable=False),
    sa.Column('game_name', sa.String(), nullable=False),
    sa.Column('nr_pokemons', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('save_name')
    )
    op.drop_table('species')
    op.drop_index(op.f('ix_pokemon_species_id'), table_name='pokemon')
    op.drop_index(op.f('ix_pokemon_species_name'), table_name='pokemon')
    op.drop_table('pokemon')
    op.drop_index(op.f('ix_save_game_name'), table_name='save')
    op.drop_table('save')
    op.drop_table('location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('party', sa.BOOLEAN(), nullable=False),
    sa.Column('nr_box', sa.INTEGER(), nullable=False),
    sa.Column('slot_number', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('save',
    sa.Column('file_name', sa.VARCHAR(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('save_name', sa.VARCHAR(), nullable=False),
    sa.Column('trainer_name', sa.VARCHAR(), nullable=True),
    sa.Column('game_name', sa.VARCHAR(), nullable=True),
    sa.Column('nr_pokemons', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_save_game_name'), 'save', ['game_name'], unique=False)
    op.create_table('pokemon',
    sa.Column('species_id', sa.INTEGER(), nullable=True),
    sa.Column('nickname', sa.VARCHAR(), nullable=True),
    sa.Column('level', sa.INTEGER(), nullable=True),
    sa.Column('is_shiny', sa.BOOLEAN(), nullable=True),
    sa.Column('nature', sa.VARCHAR(), nullable=True),
    sa.Column('ability', sa.VARCHAR(), nullable=True),
    sa.Column('iv_hp', sa.INTEGER(), nullable=True),
    sa.Column('iv_atk', sa.INTEGER(), nullable=True),
    sa.Column('iv_def', sa.INTEGER(), nullable=True),
    sa.Column('iv_spa', sa.INTEGER(), nullable=True),
    sa.Column('iv_spd', sa.INTEGER(), nullable=True),
    sa.Column('iv_spe', sa.INTEGER(), nullable=True),
    sa.Column('held_item_id', sa.INTEGER(), nullable=True),
    sa.Column('slot_number', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('species_name', sa.VARCHAR(), nullable=True),
    sa.Column('save_id', sa.INTEGER(), nullable=False),
    sa.Column('location_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['save_id'], ['save.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pokemon_species_name'), 'pokemon', ['species_name'], unique=False)
    op.create_index(op.f('ix_pokemon_species_id'), 'pokemon', ['species_id'], unique=False)
    op.create_table('species',
    sa.Column('species_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('species_id')
    )
    op.drop_table('saves')
    # ### end Alembic commands ###
